#!/bin/sh
# Usage: autmount (no arguments needed)
# Result: mounts /dev/sda1 (data HDD) to /home/sierdzio/data
# with read and write access.
if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
  echo "Usage: autmount (no arguments needed)"
  echo "Result: mounts /dev/sda1 (data HDD) to /home/sierdzio/data"
  echo "with read and write access."
else
  sudo mount -w /dev/sda1 /home/sierdzio/data
fi