#!/bin/bash
# Usage: cleanCodeDir
# Result: all makefiles and temporary files will be removed, recursively.

recursiverm() {
for d in *; do
  if [ -d "$d" ]; then
    (cd "$d"
    #echo Entered $PWD # debug
    recursiverm)
  else
    REMOVE=false
    #echo Current file $(pwd)/$d # debug
    if [[ $d == *~ ]] || [[ $d == *.o ]] || [[ $d == moc_* ]] || [[ $d == Makefile ]] || [[ $d == *.obj ]]; then
      REMOVE=true
    fi    
    
    if $REMOVE ; then
      echo Removing $(pwd)/$d
      rm $d
    fi
  fi
done
}

if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
  echo "Usage: cleanCodeDir"
  echo "Result: all makefiles and temporary files will be removed, recursively."
else
  recursiverm
fi