#!/bin/bash

# Recursive dcraw, with -T as output.
recursiverm() {
for d in *; do
  if [ -d $d ]; then
    (cd $d
    echo Entered $PWD
    recursiverm)
  else
    if [[ $d == *.CR2 ]]; then
      echo Processing $d in: $PWD
      dcraw -T $d
    fi
  fi
done
}

recursiverm