#!/bin/sh
# Usage: dist-upgrade (no arguments)
# Result: Fetches apt updates and runs apt dist-upgrade.
if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
  echo "Usage: dist-upgrade (no arguments)"
  echo "Result: Fetches updates and updates the system."
  echo "Afterwards, it runs automatic cleaning."
  echo "Works on Ubuntu family of systems, has partial support for openSUSE."
  echo
  echo "Requires root permissions."
else
  OS=$(lsb_release -a)

  UBUNTU=$(echo $OS | grep buntu)
  SUSE=$(echo $OS | grep SUSE)

  if [ -n "${UBUNTU}" ]; then
    echo "Ubuntu family, will use apt-get"
    sudo apt update
    sudo apt dist-upgrade
    sudo apt autoremove
    sudo apt autoclean
    echo "Done"
    exit
  fi

  if [ -n "${SUSE}" ]; then
    echo "SUSE family, will use zypper"
    sudo zypper refresh
    sudo zypper update
#    sudo zypper dist-upgrade
    echo "Done"
    exit
  fi

  echo "Unknown OS. Sorry..."
  exit 123
fi
