#!/bin/bash
# searches files for given messages, writes output to /home/sierdzio/temp
# Usage:
# error_grep "regexp" fileToLookInto
# example: grep_error "W32ERR" w32error.h
#
# It overwrites the file!
filename=$(basename ${2})
output=/home/sierdzio/temp/"$filename".temp

touch $output
grep "${1}" "${2}" > $output
echo "Count: " >> $output
grep -c "${1}" "${2}" >> $output