#!/bin/sh
if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
  echo "Usage: sudo linuxPostInstall"
  echo "Performs the usuall post-installation steps for my Linux installations."
  echo
  echo "Steps taken are (in this order):"
  echo "  Install build dependencies for Qt 5"
  echo "  Installs: build-essentials, git, gitk, svn, mesa-utils, yakuake, kate,"
  echo "  VLC, pbzip2, fortunes (full), cowsay, krusader"
  echo "  Uninstalls: dragonplayer"
  echo "  Updates and upgrades the whole system"
  echo
  echo "This script is not finished yet"
  echo "For now, this is only prepared for and tested on *buntu family of OSes."
  exit
fi

OS=$(lsb_release -a)
UBUNTU=$(echo $OS | grep buntu)
SUSE=$(echo $OS | grep SUSE)
CURRENT_DIR=$(pwd)

if [ -n "${UBUNTU}" ]; then
  echo "Ubuntu family"
  echo
#  echo "### Adding Linux data partition to fstab"
#  sudo mkdir /mnt/data
#  sudo chown -R $USER /mnt/data
#  sudo cp /etc/fstab /etc/fstab.bak
#  sudo cat >>/etc/fstab <<EOL
# tuxdata drive /dev/sdb5
#
#UUID=27b90427-364e-4f8a-9fc4-ad5f420b1784 /mnt/data ext4 defaults 0 3
#
#EOL

  #sudo mount -a
#  echo "### Adding symlinks to popular destinations from Linux data partition"
#  echo "  Removing dirs from $HOME"
#  rm -rf $HOME/Documents $HOME/Downloads $HOME/Pictures $HOME/Music
#  ln -s /mnt/data/documents $HOME/Documents
# ln -s /mnt/data/downloads $HOME/Downloads
#  ln -s /mnt/data/pictures $HOME/Pictures
#  ln -s /mnt/data/music $HOME/Music
#  ln -s /mnt/data $HOME/data
  echo "### Running update"
  sudo apt-get update
  echo "### Installing build dependencies"
  sudo apt-get build-dep qt5-qmake
  echo "### Installing new applications"
  sudo apt-get install build-essential git gitk mesa-utils \
       yakuake vlc pbzip2 fortunes fortunes-off cowsay #\
       #openjdk-14-jdk
  echo "### Removing unnecessary applications"
  sudo apt-get purge dragonplayer
  echo "### Running system upgrade"
  sudo apt-get dist-upgrade
  echo "### Removing obsolete packages and installation leftovers"
  sudo apt-get autoremove
  sudo apt-get autoclean
  echo "### Adding useful bash scripts (requires GitHub account)"
  cd
  git clone git@github.com:sierdzio/sierdzios-bash-scripts.git bin
  . $HOME/.profile
  cd $CURRENT_DIR
  echo "Installing oh my zsh"
  sudo apt install zsh fonts-powerline
  sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  echo "Please update .zshrc file manually"
else
  echo "Unknown OS, bailing out"
  exit 2
fi




