#! /bin/bash
if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
  echo "Usage: qt5compile (no arguments)"
  echo "Performs a full clean, configure and build of Qt5."
  echo
  echo "Does not update any sources. Needs to be run from Qt's root dir."
else
  unset QTDIR
  export PATH="$PWD/qtbase/bin:$PWD/qtrepotools/bin:$PATH"

  git submodule foreach --recursive 'git clean -dfx'

  ./configure -developer-build -opensource -confirm-license -no-gtkstyle -nomake tests -nomake examples -nomake demos
  ./build -j 9
fi

