#!/bin/sh
if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
  echo "Usage: u"
  echo "Synonym to git pull or svn up"
  echo
  echo "Requires git or svn."
else
  if [ -d .git ] || git rev-parse --git-dir > /dev/null 2>&1 ; then
    git pull
    exit
  fi
  
  if svn info . > /dev/null 2>&1 ; then
    svn up
    exit
  fi
  
  echo "Neither git not SVN repository was found"
fi